### ISSUE TITLE
Sostituzione del protocollo SSL 3.0 con TLS 1.0

### ISSUE THREAD

**Issue by g4b0** [asterixcapri/gestpaycrypt-php#1]
Ciao, questa classe sarà compatibile con le nuove specifiche di banca sella? 
https://www.gestpay.it/gestpay/sicurezza/poodle.jsp

Grazie

**Comment by TheShrike** [comment]
In base a cosa hanno risposto qui sembrerebbe di no:
https://forum.sella.it/spazioaperto/posts/list/192002.page#652403

> contestualmente alla dismissione del protocollo SSL3 verrà dismessa anche la possibilità di utilizzare il servizio di Crittografia attraverso le API GestPayCrypt e GestPayCryptHS, già da tempo deprecate, in favore dei web services WSCryptDecrypt.

**Comment by asterixcapri** [comment]
Grazie al contributo di @g4b0 ora la nuova classe [GestPayCryptWS](https://github.com/asterixcapri/gestpaycrypt-php/blob/master/lib/GestPayCryptWS.php) è compatibile con le nuove specifiche di Banca Sella.

:smile:
